# Deploy CI
# =============
# This file is aimed at deploy project over ssh
# Production stack should be simple docker
# Project should :
#  - be a node project with package.json
#  - contain script prod to deploy
# Vm should have following tools :
#  - yarn
#  - node
#  - docker
#  - hugo

name: deploy

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-18.04
    if: contains(github.event.head_commit.message, '[skip-release]') == false
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 2.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Get npm cache directory path
        id: cache-dir
        run: echo "::set-output name=dir::$(npm cache)"

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install auto
        run: |
          npm install -g auto && npm install -g @auto-it/git-tag
          export PATH=~/node_modules/.bin:$PATH
  
      - name: create labels
        if: contains(github.event.head_commit.message, '[create-labels]') == true
        run: cd auto/ && auto create-labels

      - name: Shipit release
        run: GH_TOKEN=${{ env.GH_TOKEN }} auto shipit
